### ISSUE TITLE
Make relation interface more specific

### ISSUE THREAD

**Issue by mmanciop** [xavpaice/charm-alertmanager-karma#1]
The `karma` relation is maybe too general, because it documents the connection between karma and alertmanager. But the interface has to be unique across all possible use-cases, so, if we call it just `karma`, and another relation involving karma shows up, we have a problem :-)

I would rename it to `karma-management` between Karma and Alertmanager that explains that Karma manages Alertmanager. WDYT @xavpaice ?

**Comment by xavpaice** [comment]
https://github.com/xavpaice/charm-alertmanager-karma/commit/c12fa86591c7a8997dd3ab51053c21292b72b235 updates the name to karmamanagement.
